version: '3'

tasks:
  test:
    cmds:
      - GOEXPERIMENT=synctest GODEBUG=asynctimerchan=0 TEST_OUTPUT_LOG=false gotest  ./...

  examples:
    cmds:
      - |
        for file in examples/*/main.go; do
          echo "Running $file"
          go run "$file"
          echo "----------------------"
          echo
        done

  package:
    cmds:
      - |
        : "${TAG:=$(git describe --long --tags --dirty --always | tr '/' '-')}"
        export TAG
        echo "Building flowstate:${TAG}"
        docker build --platform="linux/arm64" -t "flowstate:${TAG}" .
  publish:
    cmds:
      - |
        : "${TAG:=$(git describe --long --tags --dirty --always | tr '/' '-')}"
        export TAG
        TAG=$TAG task package

        docker tag "flowstate:$TAG" "docker.io/makasim/flowstate:$TAG"
        echo "Pushing docker.io/makasim/flowstate:$TAG"
        docker push "docker.io/makasim/flowstate:$TAG"
